# Generated by Django 5.1.3 on 2024-11-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"ordering": ("due_date",)},
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=200, verbose_name="area name"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="core.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=200, verbose_name="task name"),
        ),
    ]
