# Generated by Django 5.1.3 on 2024-11-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_schedule_options_alter_area_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="url",
            field=models.URLField(blank=True, verbose_name="consumable url"),
        ),
    ]
