# Generated by Django 5.1.4 on 2025-04-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_consumable_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="area name"),
        ),
        migrations.AlterField(
            model_name="consumable",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="quantity on-hand"),
        ),
        migrations.AlterField(
            model_name="taskconsumable",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="quantity required"),
        ),
    ]
