# Generated by Django 5.1.4 on 2025-04-13 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_area_name_alter_consumable_quantity_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("name", "area")},
        ),
    ]
