# Generated by Django 5.1.4 on 2025-04-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_task_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumable",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
